table 'Calendario Base'
	lineageTag: f688a4ef-e04c-4aad-92d9-87e2d38eba84

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0776a15a-e4c2-4411-86f7-f31a4c25eaae
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		lineageTag: e4e32a61-0c9e-40d6-99eb-212c00a9dcee
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: int64
		lineageTag: c923ee3d-a44c-40ae-b5ac-9ba2eca57e9f
		summarizeBy: none
		sourceColumn: Month

	column MonthName
		dataType: string
		lineageTag: c651c360-3695-40a0-9451-edc37bb614cc
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

	column YearMonth
		dataType: string
		lineageTag: 595f0ada-1883-4479-be71-15f2d12a972d
		summarizeBy: none
		sourceColumn: YearMonth

	partition 'Calendario Base' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "/Calendario Base.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"YearMonth", type text}}, "en-US")
				in Typed
